name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.omarrzzk }}" | docker login -u "${{ secrets.or2000omar }}" --password-stdin

      - name: Build Docker image
        run: docker build -t omarrzzk/personnummer-kontroll .

      - name: Push Docker image to DockerHub
        run: docker push omarrzzk/personnummer-kontroll
